//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAssetGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UAssetGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] dancing_cat {
            get {
                object obj = ResourceManager.GetObject("dancing_cat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] en_US {
            get {
                object obj = ResourceManager.GetObject("en_US", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAGUtils.InvokeUI(() =&gt;
        ///{
        ///    // Your code goes here
        ///    MessageBox.Show(&quot;Welcome to scripting with C# in UAssetGUI!\n\n&quot; + Interface.GetBaseForm().GetProjectName() + &quot;\n&quot; + Interface.GetDisplayVersion() + &quot;\n&quot; + UAPUtils.DisplayVersion, &quot;Hello, world!&quot;);
        ///});
        ///.
        /// </summary>
        internal static string Hello_world {
            get {
                return ResourceManager.GetString("Hello_world", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] language_codes {
            get {
                object obj = ResourceManager.GetObject("language_codes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] language_names {
            get {
                object obj = ResourceManager.GetObject("language_names", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // This script outputs a textual representation of the currently visible nodes to node_structure.txt
        ///
        ///using System.IO;
        ///
        ///UAGUtils.InvokeUI(() =&gt;
        ///{
        ///    List&lt;string&gt; nodeLabels = new List&lt;string&gt;();
        ///    TreeNode node = Interface.GetTreeView().TopNode;
        ///    while (node != null &amp;&amp; node.IsVisible)
        ///    {
        ///        int numAncestors = 0;
        ///        TreeNode parent = node.Parent;
        ///        while (parent != null)
        ///        {
        ///            numAncestors++;
        ///            parent = parent.Parent;
        ///        }
        ///        nodeL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Print_visible_nodes {
            get {
                return ResourceManager.GetString("Print_visible_nodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // this example script changes the value of all float entries in the currently selected node to 100
        ///int numChanged = 0;
        ///
        ///void DoSwaps(List&lt;PropertyData&gt; props)
        ///{
        ///    foreach (PropertyData propData in props)
        ///    {
        ///        if (propData is FloatPropertyData floatPropData)
        ///        {
        ///            floatPropData.Value = 100;
        ///            numChanged++;
        ///        }
        ///        if (propData is DoublePropertyData doublePropData)
        ///        {
        ///            doublePropData.Value = 100;
        ///            numChanged++;
        ///       [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Set_all_visible_floats_to_100 {
            get {
                return ResourceManager.GetString("Set_all_visible_floats_to_100", resourceCulture);
            }
        }
    }
}
